---

- name: Adding shark group
  group:
    name: shark
    state: present

- name: Adding shark user
  user:
    name: shark
    comment: AlgorithmicTradingPlatform user account
    group: shark
    shell: /bin/false
    home: /shark

- name: Creating shark working directory
  file:
    name: /shark
    owner: shark
    group: shark
    state: directory

- name: Creating strategies working directory
  file:
    name: /shark/strategies
    owner: shark
    group: shark
    state: directory
    
- name: Creating bin working directory
  file:
   name: /shark/bin
   owner: shark
   group: shark
   state: directory

- name: Creating our backtest web dir to store the historical back test web files
  file:
   name: /shark/backtest
   owner: shark
   group: shark
   state: directory
   mode: 0777

- name: Copying the backtest web dir index.php
  copy:
   src: strategies/backtesting/index.php
   dest: /shark/backtest/
   owner: shark
   group: shark
   mode: 0755

- name: Creating tmp cache directory
  file:
   name: /tmp/.shark
   group: shark
   owner: shark
   state: directory

- name: Synchronsing ticker data dir
  copy: 
   src: ticker-data
   dest: /shark/
   owner: shark
   group: shark

- name: Synchronsing data in strategies directory
  copy:
    src: strategies
    dest: /shark/
    owner: shark
    group: shark
    mode: 0755

- name: Copy our ASX List of companies downloaded from the ASX site. 
  copy:
    src: ASX_Listed_Companies.csv
    dest: /shark/
    owner: shark
    group: shark

- name: Copying out list of excluded tickers
  copy: 
   src: excluded_tickers.txt
   dest: /shark/

- name: Copying in our nagios ticker config generation script
  copy:
   src: process_tickers.py
   dest: /shark
   owner: shark
   group: shark
   mode: 0755

- name: Installing pyyaml for the above
  apt:
   name: python-yaml
   state: latest

- name: Copying out ticker-config.yml file
  copy:
   src: ticker-config.yml
   dest: /shark
   group: shark
   owner: shark

- name: Copying in custom UI changes - side.php
  copy:
   src: ui_patches/side.php
   dest: /tmp/nagios-4.4.6/html

- name: Copying custom logo
  copy:
   src: ui_patches/sblogo.png
   dest: /tmp/nagios-4.4.6/contrib/exfoliation/images/sblogo.png
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying main logo
  copy:
   src: ui_patches/logofullsize.png
   dest: /tmp/nagios-4.4.6/contrib/exfoliation/images/
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - status.c
  copy:
   src: ui_patches/status.c
   dest: /tmp/nagios-4.4.6/cgi
  notify: 
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - statusdata.c
  copy:
   src: ui_patches/statusdata.c
   dest: /tmp/nagios-4.4.6/common
  notify: 
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - extinfo.c
  copy:
   src: ui_patches/extinfo.c
   dest: /tmp/nagios-4.4.6/cgi
  notify:
  - rebuild-nagios
  - restart-nagios

- name: Copying in custom UI changes - extinfo.c
  copy:
   src: ui_patches/main.php
   dest: /tmp/nagios-4.4.6/html
  notify:
  - rebuild-nagios
  - restart-nagios


- meta: flush_handlers

- include: website_check.yml

- include: nagios_configuration.yml

- include: back_testing.yml

- include: check_short.yml

- name: Running plugin smoke tests
  shell: cd /shark/plugins/ && ./smoke_tests.py
  register: tests_results

- debug: 
        var: tests_results.stdout_lines

- name: Running nagios self santize to detect errors
  shell: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
  register: shell_result

- debug: 
        var: shell_result.stdout_lines
