---

- name: Adding UI refresh code for backtests
  copy:
   src: ui_refresh/ui_backtest_transactions_refresh.py
   dest: /shark/bin
   mode: 0755
   
- name: Adding UI jinja code for backtests transaction web template
  copy:
   src: ui_refresh/transaction.html.jinja
   dest: /shark/bin
   
  

