---
# tasks file for zookeeper
- name: Ensure group "zk" exists
  group:
    name: zk
    state: present
    
- name: Add zk user
  user:
    name: zk
    shell: /bin/bash
    groups: zk 
    
- name: Downloading ZooKeeper 
  shell: cd /tmp && wget -N https://apache.mirror.digitalpacific.com.au/zookeeper/zookeeper-3.6.2/apache-zookeeper-3.6.2-bin.tar.gz
  
- name: Unzipping the above
  unarchive:
   src: /tmp/apache-zookeeper-3.6.2-bin.tar.gz
   dest: /shark/
   
- name: Configuring permissions on the above
  file: 
   dest: /shark/apache-zookeeper-3.6.2-bin
   owner: zk 
   group: zk 
   recurse: yes

- name: Creating zookeeper data directory
  file:
    path: /shark/zookeeper-data
    state: directory
    owner: zk 
    group: zk 
   
- name: Adding zoo configuration file
  copy:
   src: zoo.cfg
   dest: /shark/apache-zookeeper-3.6.2-bin/conf
   owner: zk 
   group: zk 
   
- name: Adding zookeeper systemd file
  copy:
   src: zookeeper.service
   dest: /etc/systemd/system/
   
- name: Starting zookeeper
  service:
   name: zookeeper
   state: started
   enable: true
